import type { Repository, ClaimedIssue, ShameboardEntry } from "./types"

export const demoRepositories: Repository[] = [
  {
    id: "demo-repo-1",
    github_owner: "facebook",
    github_repo: "react",
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-repo-2",
    github_owner: "vercel",
    github_repo: "next.js",
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-repo-3",
    github_owner: "microsoft",
    github_repo: "vscode",
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const demoClaimedIssues: ClaimedIssue[] = [
  {
    id: "demo-issue-1",
    repository_id: "demo-repo-1",
    issue_number: 28456,
    issue_title: "Add support for async Server Components",
    issue_url: "https://github.com/facebook/react/issues/28456",
    claimer_username: "cookielicker99",
    claimer_avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=cookielicker99",
    claim_comment_id: "comment-123",
    claim_comment_text: "I'll work on this! Assigning to myself.",
    claimed_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    last_checked_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    status: "nudged",
    nudge_count: 2,
    last_nudged_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    has_linked_pr: false,
    has_commits: false,
    auto_release_at: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    repository: demoRepositories[0],
  },
  {
    id: "demo-issue-2",
    repository_id: "demo-repo-2",
    issue_number: 61234,
    issue_title: "Fix hydration mismatch in app router",
    issue_url: "https://github.com/vercel/next.js/issues/61234",
    claimer_username: "promisebreaker",
    claimer_avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=promisebreaker",
    claim_comment_id: "comment-456",
    claim_comment_text: "I can fix this, please assign!",
    claimed_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    last_checked_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: "nudged",
    nudge_count: 1,
    last_nudged_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    has_linked_pr: false,
    has_commits: false,
    auto_release_at: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    repository: demoRepositories[1],
  },
  {
    id: "demo-issue-3",
    repository_id: "demo-repo-1",
    issue_number: 28789,
    issue_title: "Improve error boundaries documentation",
    issue_url: "https://github.com/facebook/react/issues/28789",
    claimer_username: "ghostcontributor",
    claimer_avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=ghostcontributor",
    claim_comment_id: "comment-789",
    claim_comment_text: "Working on this now!",
    claimed_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    last_checked_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    status: "active",
    nudge_count: 0,
    has_linked_pr: false,
    has_commits: false,
    auto_release_at: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    repository: demoRepositories[0],
  },
  {
    id: "demo-issue-4",
    repository_id: "demo-repo-3",
    issue_number: 198765,
    issue_title: "Add vim keybindings for terminal",
    issue_url: "https://github.com/microsoft/vscode/issues/198765",
    claimer_username: "reliabledev",
    claimer_avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=reliabledev",
    claim_comment_id: "comment-101",
    claim_comment_text: "I'll take this one",
    claimed_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    last_checked_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    status: "active",
    nudge_count: 0,
    has_linked_pr: true,
    has_commits: true,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    repository: demoRepositories[2],
  },
]

export const demoShameboardEntries: ShameboardEntry[] = [
  {
    id: "demo-shame-1",
    username: "cookielicker99",
    total_abandoned: 12,
    total_completed: 2,
    reliability_score: 14,
    last_updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-shame-2",
    username: "promisebreaker",
    total_abandoned: 8,
    total_completed: 3,
    reliability_score: 27,
    last_updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-shame-3",
    username: "ghostcontributor",
    total_abandoned: 15,
    total_completed: 1,
    reliability_score: 6,
    last_updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-fame-1",
    username: "reliabledev",
    total_abandoned: 1,
    total_completed: 47,
    reliability_score: 98,
    last_updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-fame-2",
    username: "consistentcoder",
    total_abandoned: 2,
    total_completed: 38,
    reliability_score: 95,
    last_updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-fame-3",
    username: "shipperextraordinaire",
    total_abandoned: 3,
    total_completed: 29,
    reliability_score: 91,
    last_updated_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
